In [1]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', 200)

In [3]:
df_A_daily = pd.read_excel("data_folder/data.xlsx")
df_A_interval = pd.read_excel("data_folder/data.xlsx", sheet_name="A - Interval")
df_B_daily = pd.read_excel("data_folder/data.xlsx", sheet_name="B - Daily")
df_B_interval = pd.read_excel("data_folder/data.xlsx", sheet_name="B - Interval")
df_C_daily = pd.read_excel("data_folder/data.xlsx", sheet_name="C - Daily")
df_C_interval = pd.read_excel("data_folder/data.xlsx", sheet_name="C - Interval")
df_D_daily = pd.read_excel("data_folder/data.xlsx", sheet_name="D - Daily")
df_D_interval = pd.read_excel("data_folder/data.xlsx", sheet_name="D - Interval")

In [4]:

df_A_daily_removed = df_A_daily.dropna()
df_B_daily_removed = df_B_daily.dropna()
df_C_daily_removed = df_C_daily.dropna()
df_D_daily_removed = df_D_daily.dropna()
df_A_interval_removed = df_A_interval.dropna()
df_B_interval_removed = df_B_interval.dropna()
df_C_interval_removed = df_C_interval.dropna()
df_D_interval_removed = df_D_interval.dropna()

In [5]:
cv_means_a = df_A_interval_removed.groupby("Interval")["Call Volume"].mean()
cct_means_a = df_A_interval_removed.groupby("Interval")["CCT"].mean()
abd_means_a = df_A_interval_removed.groupby("Interval")["Abandoned Rate"].mean()

cv_means_b = df_B_interval_removed.groupby("Interval")["Call Volume"].mean()
cct_means_b = df_B_interval_removed.groupby("Interval")["CCT"].mean()
abd_means_b = df_B_interval_removed.groupby("Interval")["Abandoned Rate"].mean()

cv_means_c = df_C_interval_removed.groupby("Interval")["Call Volume"].mean()
cct_means_c = df_C_interval_removed.groupby("Interval")["CCT"].mean()
abd_means_c = df_C_interval_removed.groupby("Interval")["Abandoned Rate"].mean()

cv_means_d = df_D_interval_removed.groupby("Interval")["Call Volume"].mean()
cct_means_d = df_D_interval_removed.groupby("Interval")["CCT"].mean()
abd_means_d = df_D_interval_removed.groupby("Interval")["Abandoned Rate"].mean()

In [6]:
df_template = pd.read_csv("data_folder/template_forecast_v00.csv")

df_template_removed = df_template.copy()

In [7]:
def convert_HHMM(t):
    return f"{t.hour}:{t.minute:02d}"

In [8]:
cv_means_a.index = cv_means_a.index.map(convert_HHMM)
cct_means_a.index = cct_means_a.index.map(convert_HHMM)
abd_means_a.index = abd_means_a.index.map(convert_HHMM)

cv_means_b.index = cv_means_b.index.map(convert_HHMM)
cct_means_b.index = cct_means_b.index.map(convert_HHMM)
abd_means_b.index = abd_means_b.index.map(convert_HHMM)

cv_means_c.index = cv_means_c.index.map(convert_HHMM)
cct_means_c.index = cct_means_c.index.map(convert_HHMM)
abd_means_c.index = abd_means_c.index.map(convert_HHMM)

cv_means_d.index = cv_means_d.index.map(convert_HHMM)
cct_means_d.index = cct_means_d.index.map(convert_HHMM)
abd_means_d.index = abd_means_d.index.map(convert_HHMM)

In [9]:
df_template_removed["Calls_Offered_A"] = df_template_removed["Interval"].map(cv_means_a).round(0).astype(int)
df_template_removed["CCT_A"] = df_template_removed["Interval"].map(cct_means_a).round(0).astype(int)
df_template_removed["Abandoned_Rate_A"] = df_template_removed["Interval"].map(abd_means_a)
df_template_removed["Abandoned_Calls_A"] = df_template_removed["Calls_Offered_A"] * df_template_removed["Abandoned_Rate_A"]
df_template_removed["Abandoned_Calls_A"] = (df_template_removed["Abandoned_Calls_A"].round(0).astype(int))
df_template_removed["Abandoned_Rate_A"] = (df_template_removed["Abandoned_Rate_A"] * 100).round(2).astype(str) + "%"

df_template_removed["Calls_Offered_B"] = df_template_removed["Interval"].map(cv_means_b).round(0).astype(int)
df_template_removed["CCT_B"] = df_template_removed["Interval"].map(cct_means_b).round(0).astype(int)
df_template_removed["Abandoned_Rate_B"] = df_template_removed["Interval"].map(abd_means_b)
df_template_removed["Abandoned_Calls_B"] = df_template_removed["Calls_Offered_B"] * df_template_removed["Abandoned_Rate_B"]
df_template_removed["Abandoned_Calls_B"] = (df_template_removed["Abandoned_Calls_B"].round(0).astype(int))
df_template_removed["Abandoned_Rate_B"] = (df_template_removed["Abandoned_Rate_B"] * 100).round(2).astype(str) + "%"

df_template_removed["Calls_Offered_C"] = df_template_removed["Interval"].map(cv_means_c).round(0).astype(int)
df_template_removed["CCT_C"] = df_template_removed["Interval"].map(cct_means_c).round(0).astype(int)
df_template_removed["Abandoned_Rate_C"] = df_template_removed["Interval"].map(abd_means_c)
df_template_removed["Abandoned_Calls_C"] = df_template_removed["Calls_Offered_C"] * df_template_removed["Abandoned_Rate_C"]
df_template_removed["Abandoned_Calls_C"] = (df_template_removed["Abandoned_Calls_C"].round(0).astype(int))
df_template_removed["Abandoned_Rate_C"] = (df_template_removed["Abandoned_Rate_C"] * 100).round(2).astype(str) + "%"

df_template_removed["Calls_Offered_D"] = df_template_removed["Interval"].map(cv_means_d).round(0).astype(int)
df_template_removed["CCT_D"] = df_template_removed["Interval"].map(cct_means_d).round(0).astype(int)
df_template_removed["Abandoned_Rate_D"] = df_template_removed["Interval"].map(abd_means_d)
df_template_removed["Abandoned_Calls_D"] = df_template_removed["Calls_Offered_D"] * df_template_removed["Abandoned_Rate_D"]
df_template_removed["Abandoned_Calls_D"] = (df_template_removed["Abandoned_Calls_D"].round(0).astype(int))
df_template_removed["Abandoned_Rate_D"] = (df_template_removed["Abandoned_Rate_D"] * 100).round(2).astype(str) + "%"

df_template_removed

,Month,Day,Interval,Calls_Offered_A,Abandoned_Calls_A,Abandoned_Rate_A,CCT_A,Calls_Offered_B,Abandoned_Calls_B,Abandoned_Rate_B,CCT_B,Calls_Offered_C,Abandoned_Calls_C,Abandoned_Rate_C,CCT_C,Calls_Offered_D,Abandoned_Calls_D,Abandoned_Rate_D,CCT_D
0,August,1,0:00,5,0,1.71%,393,30,1,1.74%,310,64,0,0.63%,325,39,0,0.74%,313
1,August,1,0:30,4,0,2.31%,337,21,0,0.84%,298,48,0,0.36%,321,27,0,0.27%,325
2,August,1,1:00,3,0,2.28%,371,10,0,2.09%,356,35,0,0.94%,317,21,0,0.5%,340
3,August,1,1:30,2,0,2.8%,323,6,0,3.25%,321,26,0,1.08%,319,16,0,1.1%,332
4,August,1,2:00,2,0,0.9%,371,4,0,1.6%,334,18,0,2.64%,296,11,0,2.83%,334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,August,31,21:30,22,0,1.63%,317,117,1,0.72%,322,231,1,0.28%,335,132,2,1.17%,319
1484,August,31,22:00,18,0,0.67%,320,95,1,0.89%,316,190,1,0.48%,331,108,1,0.98%,320
1485,August,31,22:30,13,2,13.16%,311,75,1,0.78%,308,151,0,0.33%,323,90,1,0.67%,316
1486,August,31,23:00,10,1,6.74%,330,56,0,0.69%,299,116,0,0.2%,320,70,0,0.37%,316
1487,August,31,23:30,8,0,2.57%,296,43,0,0.57%,300,92,0,0.28%,319,55,0,0.62%,311

In [10]:
df_template_removed.to_csv("forecast_v01.csv", index = False)

In [11]:
# from sklearn.linear_model import PoissonRegressor
# from sklearn.linear_model import LinearRegression
# from sklearn.linear_model import LogisticRegression

import statsmodels.formula.api as smf

In [12]:
import datetime

def convert_datetime(s):
    hour, min = map(int, s.split(":")) 
    return datetime.time(hour, min)

In [13]:
df_basic_regression = df_template.copy()

In [14]:
# convert call_volume to int (initially float)
df_A_interval_removed['Call Volume'] = df_A_interval_removed['Call Volume'].astype(int)

# poisson regression based on the interval and day
model_a_cv = smf.poisson("Q('Call Volume') ~ C(Interval) + C(Day)", 
                                       data=df_A_interval_removed).fit()

# convert str to datetime 
df_basic_regression['Interval'] = df_basic_regression['Interval'].apply(convert_datetime)

# fill column with predicted values of template df
df_basic_regression["Calls_Offered_A"] = model_a_cv.predict(df_basic_regression).round(0).astype(int)
df_basic_regression

Optimization terminated successfully.
         Current function value: 8.626167
         Iterations 9

C:\Users\csalg\AppData\Local\Temp\ipykernel_19220\3492057268.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_A_interval_removed['Call Volume'] = df_A_interval_removed['Call Volume'].astype(int)

,Month,Day,Interval,Calls_Offered_A,Abandoned_Calls_A,Abandoned_Rate_A,CCT_A,Calls_Offered_B,Abandoned_Calls_B,Abandoned_Rate_B,CCT_B,Calls_Offered_C,Abandoned_Calls_C,Abandoned_Rate_C,CCT_C,Calls_Offered_D,Abandoned_Calls_D,Abandoned_Rate_D,CCT_D
0,August,1,00:00:00,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,August,1,00:30:00,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,August,1,01:00:00,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,August,1,01:30:00,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,August,1,02:00:00,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,August,31,21:30:00,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,August,31,22:00:00,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,August,31,22:30:00,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1486,August,31,23:00:00,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1487,August,31,23:30:00,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# plt.figure(figsize=(18, 6))
# sns.scatterplot(x="Interval", y="CCT", data=df_A_interval_removed)
# plt.xticks(rotation=45)
# plt.show()

In [16]:
df_A_interval_removed["Calls_Offered_A"] = (df_A_interval_removed["Call Volume"] - df_A_interval_removed["Abandoned Calls"]).round(0).astype(int)
df_A_interval_removed

C:\Users\csalg\AppData\Local\Temp\ipykernel_19220\3934156945.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_A_interval_removed["Calls_Offered_A"] = (df_A_interval_removed["Call Volume"] - df_A_interval_removed["Abandoned Calls"]).round(0).astype(int)

,Month,Day,Interval,Service Level,Call Volume,Abandoned Calls,Abandoned Rate,CCT,Calls_Offered_A
0,April,1,00:00:00,1.0000,5,0.0,0.0000,137.60,5
1,April,1,00:30:00,1.0000,5,0.0,0.0000,263.40,5
2,April,1,01:00:00,1.0000,4,0.0,0.0000,333.25,4
3,April,1,01:30:00,1.0000,3,0.0,0.0000,170.00,3
4,April,1,02:00:00,1.0000,1,0.0,0.0000,667.00,1
...,...,...,...,...,...,...,...,...,...
4078,June,30,21:30:00,0.9688,34,2.0,0.0588,319.81,32
4079,June,30,22:00:00,1.0000,23,0.0,0.0000,300.22,23
4080,June,30,22:30:00,0.8333,13,1.0,0.0769,189.50,12
4081,June,30,23:00:00,0.8000,10,0.0,0.0000,323.10,10
4082,June,30,23:30:00,1.0000,13,0.0,0.0000,247.46,13

In [ ]:
model_a_cct = smf.ols("Q('CCT') ~ C(Interval) + C(Day) + Q('Calls_Offered_A')", 
                      data=df_A_interval_removed).fit()

df_basic_regression["CCT_A"] = model_a_cct.predict(df_basic_regression)
df_basic_regression

,Month,Day,Interval,Calls_Offered_A,Abandoned_Calls_A,Abandoned_Rate_A,CCT_A,Calls_Offered_B,Abandoned_Calls_B,Abandoned_Rate_B,CCT_B,Calls_Offered_C,Abandoned_Calls_C,Abandoned_Rate_C,CCT_C,Calls_Offered_D,Abandoned_Calls_D,Abandoned_Rate_D,CCT_D
0,August,1,00:00:00,5,NaN,NaN,374.401851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,August,1,00:30:00,4,NaN,NaN,318.839086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,August,1,01:00:00,3,NaN,NaN,351.805866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,August,1,01:30:00,2,NaN,NaN,305.395604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,August,1,02:00:00,2,NaN,NaN,353.503453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,August,31,21:30:00,17,NaN,NaN,293.221570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,August,31,22:00:00,14,NaN,NaN,295.883183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,August,31,22:30:00,10,NaN,NaN,288.267712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1486,August,31,23:00:00,8,NaN,NaN,306.241289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1487,August,31,23:30:00,6,NaN,NaN,273.076433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
import statsmodels.api as sm

In [24]:
model_a_abd = smf.glm("Q('Abandoned Rate') ~ C(Interval) + C(Day)",
                        data=df_A_interval_removed, family = sm.families.Binomial()).fit()

df_basic_regression["Abandoned_Rate_A"] = model_a_abd.predict(df_basic_regression)
df_basic_regression

,Month,Day,Interval,Calls_Offered_A,Abandoned_Calls_A,Abandoned_Rate_A,CCT_A,Calls_Offered_B,Abandoned_Calls_B,Abandoned_Rate_B,CCT_B,Calls_Offered_C,Abandoned_Calls_C,Abandoned_Rate_C,CCT_C,Calls_Offered_D,Abandoned_Calls_D,Abandoned_Rate_D,CCT_D
0,August,1,00:00:00,5,NaN,0.037960,374.401851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,August,1,00:30:00,4,NaN,0.049922,318.839086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,August,1,01:00:00,3,NaN,0.048953,351.805866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,August,1,01:30:00,2,NaN,0.058645,305.395604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,August,1,02:00:00,2,NaN,0.018942,353.503453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,August,31,21:30:00,17,NaN,0.026455,293.221570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,August,31,22:00:00,14,NaN,0.010960,295.883183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,August,31,22:30:00,10,NaN,0.202786,288.267712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1486,August,31,23:00:00,8,NaN,0.106866,306.241289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1487,August,31,23:30:00,6,NaN,0.041366,273.076433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df_basic_regression["Abandoned_Calls_A"] = df_basic_regression["Calls_Offered_A"] * df_basic_regression["Abandoned_Rate_A"]
df_basic_regression["Abandoned_Calls_A"] = (df_basic_regression["Abandoned_Calls_A"].round(0).astype(int))

df_basic_regression

,Month,Day,Interval,Calls_Offered_A,Abandoned_Calls_A,Abandoned_Rate_A,CCT_A,Calls_Offered_B,Abandoned_Calls_B,Abandoned_Rate_B,CCT_B,Calls_Offered_C,Abandoned_Calls_C,Abandoned_Rate_C,CCT_C,Calls_Offered_D,Abandoned_Calls_D,Abandoned_Rate_D,CCT_D
0,August,1,00:00:00,5,0,0.037960,374.401851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,August,1,00:30:00,4,0,0.049922,318.839086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,August,1,01:00:00,3,0,0.048953,351.805866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,August,1,01:30:00,2,0,0.058645,305.395604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,August,1,02:00:00,2,0,0.018942,353.503453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,August,31,21:30:00,17,0,0.026455,293.221570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,August,31,22:00:00,14,0,0.010960,295.883183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,August,31,22:30:00,10,2,0.202786,288.267712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1486,August,31,23:00:00,8,1,0.106866,306.241289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1487,August,31,23:30:00,6,0,0.041366,273.076433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_template_removed.to_csv("forecast_v02.csv", index = False)